製作了一些超鏈接及UI升級
waterblock79/waterfall pull request #4
Opened 2021-06-15 06:18 UTC by wuxian425

如題

2021-06-15 08:59 UTC, waterblock79 requested changes
兄弟 我直说吧 你很多翻译真的不太行... 有很多地方也没必要改的，并且，请不要使用外部资源（尤其是图床，可以存到assets）

2021-06-15 08:59 UTC, waterblock79 commented on README.md
> +您需要安装 Git 环境，並Fork本项目。
上面的serve足矣，无需此项

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> -      <v-toolbar-title>Waterfall Project</v-toolbar-title>
无需翻译waterfall project的英文

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +            <template v-else>没有侦测到设备</template>
用词不准确，或许使用「设备未连接」更佳

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +            >Wifi连结模式
兄弟 你讲话很弯弯腔喔

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +              src="https://upload.cc/i1/2021/05/23/82jZQR.png"
不要使用外部http资源，这里使用安卓的图标其实无需修改的

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +			<v-text>瀑布安卓设备管理器</v-text>
这里显示设备名称刚好，可以向用户传达点我就可以查看设备的意向

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +              <v-list-item-title>关于</v-list-item-title>
关于项目

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +      <template v-if="devices.length > 0 && functionChosen != null">
这里的代码至少能跑起来了，勿动

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +              <div class="text-h4 ml-3">咦，设备去哪了呢？Σ(っ °Д °;)っ口</div>
未连接到设备

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +            Step1.进入「设置」中的「关于手机」，连续点击十次「安卓版本号」。<br />
无需变动

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +          <span class="card-title">Wifi连结</span>
无需变动

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> -              出<b>错</b>了 !
这里其实粗体一个字「错」比粗体「出错」观感更好

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +              你<b>没有成功的配置</b> Platform Tools  !
这块如果「没有成功的配置」前置的话，给人的感觉就是用户的错，用户没搞好

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +                    <v-btn text @click="e1 = 2"> ➜下一步➜ </v-btn>
无需修改

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
>                        </v-btn>
同 这里无需修改

2021-06-15 08:59 UTC, waterblock79 commented on src/App.vue
> +        { text: "安装管理", icon: "apps" },
翻译不准确

2021-06-15 08:59 UTC, waterblock79 commented on src/components/AboutProject.vue
> +    <div class="ma-12 text-center font-weight-light">
尽量不要链接到外部地址

2021-06-15 08:59 UTC, waterblock79 commented on src/components/AboutProject.vue
> +  src="https://upload.cc/i1/2021/05/23/82jZQR.png"
不要使用外部资源

2021-06-15 08:59 UTC, waterblock79 commented on src/components/AboutProject.vue
> +      <p>对新手友好的 Android 设备管理工具</p>
无需修改

2021-06-15 08:59 UTC, waterblock79 commented on src/components/AboutProject.vue
>      <v-list class="ml-3">
这块本来就是设置，我是想在这里加一个清除文件管理中的temp的，但是忘了

2021-06-15 08:59 UTC, waterblock79 commented on src/components/FileManager.vue
> +                >{{ contextmenu.item.size }} 字节（bit）（
无需添加

2021-06-15 09:15 UTC, wuxian425 reviewed
我盡力修改

2021-06-15 09:15 UTC, wuxian425 commented on README.md
> +您需要安装 Git 环境，並Fork本项目。
嗯

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> -      <v-toolbar-title>Waterfall Project</v-toolbar-title>
嗯

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +            <template v-else>没有侦测到设备</template>
使用谷歌翻譯之用詞爲“沒有設備”。

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +            >Wifi连结模式
或許使用：利用Wifi連接設備 會更佳

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +              src="https://upload.cc/i1/2021/05/23/82jZQR.png"
個人認爲安卓圖標不是很漂亮

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +			<v-text>瀑布安卓设备管理器</v-text>
那您可以在未連接設備時顯示設備未連接：）

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +      <template v-if="devices.length > 0 && functionChosen != null">
這裏我是從您的代碼中拷出來的呦

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +              <div class="text-h4 ml-3">咦，设备去哪了呢？Σ(っ °Д °;)っ口</div>
可愛ww

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +            Step1.进入「设置」中的「关于手机」，连续点击十次「安卓版本号」。<br />
ok

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> -              出<b>错</b>了 !
是嗎az

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +              你<b>没有成功的配置</b> Platform Tools  !
那可以使用 “Platform Tools尚未配置，請依照下方指示進行配置”

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
>                        </v-btn>
最後我認爲是可以修改的

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +                    <v-btn text @click="e1 = 2"> ➜下一步➜ </v-btn>
好

2021-06-15 09:15 UTC, wuxian425 commented on src/App.vue
> +        { text: "安装管理", icon: "apps" },
有些我是使用較口語化的翻譯，畢竟您的口號是讓刷機小白都可以輕鬆使用，可能利用口語化的方式較好！：）

2021-06-15 09:15 UTC, wuxian425 commented on src/components/AboutProject.vue
> +    <div class="ma-12 text-center font-weight-light">
爲何

2021-06-15 09:15 UTC, wuxian425 commented on src/components/AboutProject.vue
> +  src="https://upload.cc/i1/2021/05/23/82jZQR.png"
同，爲何

2021-06-15 09:15 UTC, wuxian425 commented on src/components/AboutProject.vue
> +      <p>对新手友好的 Android 设备管理工具</p>
UI修改

2021-06-15 09:15 UTC, wuxian425 commented on src/components/AboutProject.vue
>      <v-list class="ml-3">
既然尚未使用，那或許暫時使用path會更佳

2021-06-15 09:15 UTC, wuxian425 commented on src/components/FileManager.vue
> +                >{{ contextmenu.item.size }} 字节（bit）（
好

2021-08-11 03:11 UTC, waterblock79 reviewed
我感觉有些的话，我们的用语环境不太一样，所以有一些用词不太一样，不如保持现状，或者以一些简单的英文来代替？

2021-08-11 03:11 UTC, waterblock79 commented on src/App.vue
> +              src="https://upload.cc/i1/2021/05/23/82jZQR.png"
尽量要风格统一吧，和下面的图标风格一样可能会更好咯

2021-08-11 03:11 UTC, waterblock79 commented on src/App.vue
> +			<v-text>瀑布安卓设备管理器</v-text>
okey

2021-08-11 03:11 UTC, waterblock79 commented on src/App.vue
> -              出<b>错</b>了 !
这样的重心或许就偏向在了**错**，给用户一个警醒的感觉。

2021-08-11 03:11 UTC, waterblock79 commented on src/App.vue
>                        </v-btn>
那可以折中一下，改为“完成”XD

2021-08-11 03:11 UTC, waterblock79 commented on src/components/AboutProject.vue
> +    <div class="ma-12 text-center font-weight-light">
如果需要使用外部资源，请将其存储在 `/src/assets`

2021-08-11 03:11 UTC, waterblock79 commented on src/components/AboutProject.vue
> +  src="https://upload.cc/i1/2021/05/23/82jZQR.png"
同，如上

2021-08-11 03:11 UTC, waterblock79 commented on src/components/AboutProject.vue
>      <v-list class="ml-3">
是这样的，上面有这个项目的介绍，大概可以就是设置吧

2021-08-21 07:25 UTC, wuxian425 commented on src/App.vue
> +              src="https://upload.cc/i1/2021/05/23/82jZQR.png"
喔

2021-08-21 07:25 UTC, wuxian425 commented on src/components/AboutProject.vue
> +    <div class="ma-12 text-center font-weight-light">
喔

2021-08-21 07:25 UTC, wuxian425 commented on src/components/AboutProject.vue
> +  src="https://upload.cc/i1/2021/05/23/82jZQR.png"
喔

2021-08-21 07:25 UTC, wuxian425 commented on src/components/AboutProject.vue
>      <v-list class="ml-3">
行

2023-06-01 12:00 UTC, closed without merging